name = "cloudflare-paas"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[ dispatch_namespaces ]]
binding = "dispatcher"
namespace = "cloudflare-paas" # make sure this is the same as the DISPATCH_NAMESPACE_NAME var

[[ d1_databases ]]
binding = "DB"
database_name = "cloudflare-paas"
database_id = ""
preview_database_id = ""

[vars]
DISPATCH_NAMESPACE_NAME = "cloudflare-paas"
DISPATCH_NAMESPACE_ACCOUNT_ID = ""
# The necessary secrets are:
# - DISPATCH_NAMESPACE_API_TOKEN
# - JWT_SECRET
# - GITHUB_CLIENT_ID
# - GITHUB_CLIENT_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
